### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by CLfamilaris** [mon/spice-drs-pad#3]
Hi, I'd like to basically copy your homework and use the shader you made for the LEDs in [my own project](https://github.com/CLfamilaris/VRDOM), but this repo doesn't have a license. Does that mean it'd be allowed?

**Comment by mon** [comment]
Hey, nice catch. I added the MIT license. I wanted to do unlicense, but it felt sketchy since I'm bundling the MIT licensed Pixi.js in the repo.

I'm not too fussed about including the entire copyright, `LED code from mon` is enough of a shoutout for me :)
