### ISSUE TITLE
Does not light up in version 2020121400

### ISSUE THREAD

**Issue by mktm235** [mon/spice-drs-pad#6]
I am using spice2x, it works on 20221214, but the LED does not light on 20201214. I was using 20201214 because when I start 20221214 it crashes at the title screen.

**Comment by mon** [comment]
Can you confirm that you're using the same config, there are no real obvious errors, it just "doesn't work"?

**Comment by mktm235** [comment]
Sorry, it's resolved. The cause was that once it was closed, the spice2x API was not terminated properly and the process remained. Therefore, when I started DRS again, it did not work.

**Comment by mon** [comment]
Glad to hear it was an easy fix! Enjoy :)
